//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.01.20 at 09:58:07 PM MSK 
//


package com.grammyweb.jaxbgenerated;

import jakarta.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="musicBandId" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="schema" type="{http://example.com/please}SOAPSingleBaseSchema"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "musicBandId",
    "schema"
})
@XmlRootElement(name = "CreateSingleRequest", namespace = "http://example.com/please")
public class CreateSingleRequest {

    protected long musicBandId;
    @XmlElement(required = true)
    protected SOAPSingleBaseSchema schema;

    /**
     * Gets the value of the musicBandId property.
     * 
     */
    public long getMusicBandId() {
        return musicBandId;
    }

    /**
     * Sets the value of the musicBandId property.
     * 
     */
    public void setMusicBandId(long value) {
        this.musicBandId = value;
    }

    /**
     * Gets the value of the schema property.
     * 
     * @return
     *     possible object is
     *     {@link SOAPSingleBaseSchema }
     *     
     */
    public SOAPSingleBaseSchema getSchema() {
        return schema;
    }

    /**
     * Sets the value of the schema property.
     * 
     * @param value
     *     allowed object is
     *     {@link SOAPSingleBaseSchema }
     *     
     */
    public void setSchema(SOAPSingleBaseSchema value) {
        this.schema = value;
    }

}
