//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.01.20 at 09:58:07 PM MSK 
//


package com.grammyweb.jaxbgenerated;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example.please package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.please
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CreateRewardRequest }
     * 
     */
    public CreateRewardRequest createCreateRewardRequest() {
        return new CreateRewardRequest();
    }

    /**
     * Create an instance of {@link CreateSingleRequest }
     * 
     */
    public CreateSingleRequest createCreateSingleRequest() {
        return new CreateSingleRequest();
    }

    /**
     * Create an instance of {@link SOAPSingleBaseSchema }
     * 
     */
    public SOAPSingleBaseSchema createSOAPSingleBaseSchema() {
        return new SOAPSingleBaseSchema();
    }

    /**
     * Create an instance of {@link SOAPRewardReadSchema }
     * 
     */
    public SOAPRewardReadSchema createSOAPRewardReadSchema() {
        return new SOAPRewardReadSchema();
    }

    /**
     * Create an instance of {@link SOAPRewardBaseSchema }
     * 
     */
    public SOAPRewardBaseSchema createSOAPRewardBaseSchema() {
        return new SOAPRewardBaseSchema();
    }

    /**
     * Create an instance of {@link SOAPSingleReadSchema }
     * 
     */
    public SOAPSingleReadSchema createSOAPSingleReadSchema() {
        return new SOAPSingleReadSchema();
    }

}
