//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.01.20 at 09:58:07 PM MSK 
//


package com.grammyweb.jaxbgenerated;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SoapMusicGenre.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="SoapMusicGenre"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="ROCK"/&gt;
 *     &lt;enumeration value="RAP"/&gt;
 *     &lt;enumeration value="POST_ROCK"/&gt;
 *     &lt;enumeration value="PUNK_ROCK"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "SoapMusicGenre")
@XmlEnum
public enum SoapMusicGenre {

    ROCK,
    RAP,
    POST_ROCK,
    PUNK_ROCK;

    public String value() {
        return name();
    }

    public static SoapMusicGenre fromValue(String v) {
        return valueOf(v);
    }

}
