spring:
    datasource:
        url: ${DB_URL}
        username: ${DB_USER}
        password: ${DB_PWD}
    jpa:
        database: postgresql
        generate-ddl: true
    sql:
        init:
            mode: always

    application:
        name: music-bands-service


springdoc:
    swagger-ui:
        disable-swagger-default-url: true
        path: /docs
    default-produces-media-type: "application/json"
    default-consumes-media-type: "application/json"


server:
    port: 8444
    ssl:
        key-store-type: JKS
        key-alias: *
        key-store: *
        key-store-password: *
        key-password: *
        enabled: true
        trust-store: *
        trust-store-password: *


music-band-service:
    url: ${MUSICBANDS_SERVICE_URL:https://localhost}
    port: ${MUSICBANDS_SERVICE_PORT:8443}
